title: cuda learning log
author: Niyar Barman
description: learning cuda programming from scratch
url: https://niyarrbarman.github.io/cuda
baseurl: /cuda

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: null

# Navigation
header_pages:
  - README.md
